// templates/react-vite/src/main.tsx
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import "./index.css";
import App from "./app.tsx";

// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
createRoot(globalThis.document.querySelector("#root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// packages/solid-components/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";

import "./index.css";
import App from "./app";

const root = document.querySelector("#root");

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    "Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?",
  );
}

render(() => {
  return <App />;
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
}, root!);
