// apps/sterett-react/src/main.tsx
import { RouterProvider } from "@tanstack/react-router";
import { StrictMode } from "react";

import "./index.css";

import ReactDOM from "react-dom/client";

import { router } from "./routes/route-tree.ts";

// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
ReactDOM.createRoot(document.querySelector("#root")!).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
);

// packages/solid-components/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web";

import "./index.css";
import App from "./app";

const root = document.querySelector("#root");

if (import.meta.env.DEV && !(root instanceof HTMLElement)) {
  throw new Error(
    "Root element not found. Did you forget to add it to your index.html? Or maybe the id attribute got misspelled?",
  );
}

render(() => {
  return <App />;
// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
}, root!);
