// apps/ethang/src/components/top-card.tsx
import { Avatar, Button, Card, CardBody, Image, Link } from "@heroui/react";
import { MailIcon } from "lucide-react";

import profileImage from "../assets/profile.jpeg";
import { GithubIcon } from "./svg/github-icon.tsx";
import { LinkedinIcon } from "./svg/linkedin-icon.tsx";
import { TypographyH2 } from "./typography/typography-h2.tsx";

export const TopCard = () => {
  return (
    <Card>
      <CardBody>
        <div className="grid grid-cols-[auto_1fr] gap-4">
          <Avatar src={profileImage} alt="profile image" className="size-24" />
          <div className="grid">
            <TypographyH2>Ethan Glover</TypographyH2>
            <div className="my-4 flex flex-wrap items-center gap-4">
              <Link
                isExternal
                className="text-foreground"
                href="https://www.linkedin.com/in/ethan-glover/"
              >
                <LinkedinIcon />
              </Link>
              <Link
                isExternal
                className="text-foreground"
                href="https://github.com/eglove"
              >
                <GithubIcon />
              </Link>
              <Link
                isExternal
                className="text-foreground"
                href="mailto:hello@ethang.email"
              >
                <MailIcon />
              </Link>
              <Link
                isExternal
                className="text-foreground"
                href="https://frontendmasters.com/u/ethang/"
              >
                <Image
                  alt="Frontend Masters"
                  src="/images/frontend-masters-icon.png"
                />
              </Link>
              <Link
                isExternal
                className="text-foreground"
                href="https://app.pluralsight.com/profile/ethan-glover-e9"
              >
                <Image
                  width="25"
                  height="25"
                  alt="Pluralsight"
                  src="/images/pluralsight-icon.png"
                />
              </Link>
              <Button
                as={Link}
                size="sm"
                isExternal
                color="primary"
                href="https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7316126013938143232"
              >
                Subscribe to my Newsletter
              </Button>
              <Button
                as={Link}
                size="sm"
                isExternal
                href="https://cal.com/ethan-glover/meet"
              >
                Schedule a Meeting
              </Button>
            </div>
          </div>
        </div>
      </CardBody>
    </Card>
  );
};

// apps/ethang-angular/src/app/components/top-card/top-card.component.ts
import { NgOptimizedImage } from "@angular/common";
import { ChangeDetectionStrategy, Component, input } from "@angular/core";
import { twMerge } from "tailwind-merge";

import { TypographyH2Component } from "../typography-h2/typography-h2.component.js";

@Component({
  selector: "app-top-card",
  imports: [TypographyH2Component, NgOptimizedImage],
  templateUrl: "./top-card.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TopCardComponent {
  public readonly className = input<string>("");
  protected readonly twMerge = twMerge;

  protected createClass() {
    return twMerge(
      "rounded-xl border bg-card text-card-foreground shadow-sm",
      this.className(),
    );
  }
}

<div [class]="createClass()">
  <div class="p-6">
    <div class="grid grid-cols-[auto_1fr] gap-4">
      <img
        height="200"
        width="200"
        ngSrc="/images/profile.jpeg"
        alt="profile image"
        class="h-24 w-24 rounded-full object-cover"
      />
      <div class="grid">
        <app-typography-h2>Ethan Glover</app-typography-h2>
        <div class="my-4 flex flex-wrap items-center gap-4">
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://www.linkedin.com/in/ethan-glover/"
          >
            <svg
              width="24"
              fill="none"
              height="24"
              stroke-width="2"
              aria-hidden="true"
              viewBox="0 0 24 24"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="lucide lucide-linkedin"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"
              />
              <rect x="2" y="9" width="4" height="12" />
              <circle r="2" cx="4" cy="4" />
            </svg>
          </a>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="https://github.com/eglove"
          >
            <svg
              width="24"
              fill="none"
              height="24"
              stroke-width="2"
              aria-hidden="true"
              viewBox="0 0 24 24"
              stroke="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              xmlns="http://www.w3.org/2000/svg"
              class="lucide lucide-github"
            >
              <path
                d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4"
              />
              <path d="M9 18c-4.51 2-5-2-7-2" />
            </svg>
          </a>
          <a
            target="_blank"
            rel="noopener noreferrer"
            href="mailto:hello@ethang.email"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="lucide lucide-mail"
            >
              <rect width="20" height="16" x="2" y="4" rx="2" />
              <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
            </svg>
          </a>
          <a
            target="_blank"
            rel="noopener noreferrer"
            class="border-2 border-blue-500 py-1 px-2 rounded-xl hover:bg-blue-500"
            href="https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7316126013938143232"
          >
            Subscribe to my Newsletter
          </a>
          <a
            target="_blank"
            rel="noopener noreferrer"
            class="border-2 py-1 px-2 rounded-xl hover:bg-slate-900"
            href="https://cal.com/ethan-glover/meet"
          >
            Schedule a Meeting
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
