// apps/ethang/src/components/typography/typography-h1.tsx
import type { PropsWithChildren } from "react";

import { twMerge } from "tailwind-merge";

type TypographyH1Properties = { className?: string } & PropsWithChildren;

export const TypographyH1 = ({
  children,
  className,
}: Readonly<TypographyH1Properties>) => {
  return (
    <h2
      className={twMerge(
        "scroll-m-20 text-center text-4xl font-extrabold tracking-tight text-balance",
        className,
      )}
    >
      {children}
    </h2>
  );
};

// apps/ethang-angular/src/app/components/typography-h1/typography-h1.component.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";
import { twMerge } from "tailwind-merge";

@Component({
  selector: "app-typography-h1",
  imports: [],
  templateUrl: "./typography-h1.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TypographyH1Component {
  public readonly className = input<string>("");
  protected readonly twMerge = twMerge;
}

<h1
  [class]="`${twMerge(`scroll-m-20 text-center text-4xl font-extrabold tracking-tight text-balance ${className()}`)}`"
>
  <ng-content />
</h1>
