// apps/ethang-angular/src/app/components/typography-h2/typography-h2.component.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";
import { twMerge } from "tailwind-merge";

@Component({
  selector: "app-typography-h2",
  imports: [],
  templateUrl: "./typography-h2.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TypographyH2Component {
  public readonly className = input<string>("");
  protected readonly twMerge = twMerge;
}

<h2
  [class]="`${twMerge(`scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0 ${className()}`)}`"
>
  <ng-content />
</h2>

// packages/react-components/src/components/typography/typography-h2.tsx
import type { PropsWithChildren } from "react";

import { cn } from "@/lib/utils.ts";

type TypographyH2Properties = PropsWithChildren<{
  className?: string;
}>;

export const TypographyH2 = ({
  children, className,
}: Readonly<TypographyH2Properties>) => {
  return (
    <h1 className={cn("scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0", className)}>
      {children}
    </h1>
  );
};
