// apps/ethang-angular/src/app/components/typography-p/typography-p.component.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";
import { twMerge } from "tailwind-merge";

@Component({
  selector: "app-typography-p",
  imports: [],
  templateUrl: "./typography-p.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TypographyPComponent {
  public readonly className = input<string>("");
  protected readonly twMerge = twMerge;
}

<p [class]="`${twMerge(`leading-7 not-first:mt-6 ${className()}`)}`">
  <ng-content />
</p>

// apps/ethang/src/components/typography/typography-p.tsx
import type { PropsWithChildren } from "react";

import { twMerge } from "tailwind-merge";

type TypographyPProperties = {
  className?: string;
};

export const TypographyP = ({
  children,
  className,
}: Readonly<PropsWithChildren<TypographyPProperties>>) => {
  return (
    <p className={twMerge("leading-7 not-first:mt-6", className)}>{children}</p>
  );
};
