// apps/job-search/src/components/typography/typography-h2.tsx
import type { PropsWithChildren } from "react";

import { twMerge } from "tailwind-merge";

type TypographyH2Properties = Readonly<
  {
    className?: string;
  } & PropsWithChildren
>;

export const TypographyH2 = ({
  children,
  className,
}: TypographyH2Properties) => {
  return (
    <h2
      className={twMerge(
        "scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0",
        className,
      )}
    >
      {children}
    </h2>
  );
};

// apps/ethang-angular/src/app/components/typography-h2/typography-h2.component.ts
import { ChangeDetectionStrategy, Component, input } from "@angular/core";
import { twMerge } from "tailwind-merge";

@Component({
  selector: "app-typography-h2",
  imports: [],
  templateUrl: "./typography-h2.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TypographyH2Component {
  public readonly className = input<string>("");
  protected readonly twMerge = twMerge;
}

<h2
  [class]="`${twMerge(`scroll-m-20 border-b pb-2 text-3xl font-semibold tracking-tight first:mt-0 ${className()}`)}`"
>
  <ng-content />
</h2>
