// apps/ethang-angular/src/app/routes/courses.component.ts
import { ChangeDetectionStrategy, Component, inject } from "@angular/core";

import { ResourceBuilder } from "../services/resource-builder.service.js";
import { SanityService } from "../services/sanity.service.js";

@Component({
  selector: "app-courses",
  imports: [],
  templateUrl: "./courses.component.html",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CoursesComponent {
  private readonly resourceBuilder = inject(ResourceBuilder);
  private readonly getPaths = async () => this.sanity.getPaths();

  public readonly paths = this.resourceBuilder.createResourceLoader(
    "GetPaths",
    [],
    this.getPaths,
  );

  private readonly sanity = inject(SanityService);
}

<app-main-layout>
  <div class="mx-auto max-w-4xl">
    <app-typography-h1 className="mb-4">
      Recommended Courses
    </app-typography-h1>
    <app-typography-p
      >This list is meant as a way to provide a straightforward curriculum of
      what you need to learn for development. It's updated constantly, but at
      any given point in time, I believe this is the best way to get started
      with, and learn everything you need to know to work with the web and
      beyond.</app-typography-p
    >
    <app-typography-p className="my-4"
      >These
      @if (courseCountResource.hasValue()) {
        <span class="text-amber-500"
          >{{ courseCountResource.value() }} courses</span
        >
      } @else {
        courses
      }
      will take a while to get through, so I recommend signing up for Pro
      accounts instead of buying one-time courses. I've optimized the list to
      focus on one platform at a time. When there is a series of Udemy courses,
      sign up for Udemy Pro, cancel it when you're done, and so
      on.</app-typography-p
    >
    @if (pathsResource.isLoading()) {
      <div class="flex animate-pulse flex-col gap-4">
        <div class="h-8 w-1/4 rounded bg-slate-800"></div>
        <div class="h-4 w-full rounded bg-slate-800"></div>
        <div class="h-4 w-full rounded bg-slate-800"></div>
      </div>
    } @else {
      <div class="grid gap-8">
        @for (path of paths(); track path._id) {
          <section
            class="rounded-lg border border-slate-800 bg-slate-900/50 p-4"
          >
            <header class="group mb-4 border-b border-slate-800 pb-2">
              <app-typography-h2 className="text-2xl">
                <a
                  class="group-hover:text-blue-400 group-hover:underline"
                  target="_blank"
                  [href]="path.url"
                >
                  {{ path.name.split(":")[0]
                  }}{{ path.name.split(":")[1] ? ":" : "" }}
                  <span class="text-amber-500">{{
                    path.name.split(":").slice(1).join(" ")
                  }}</span>
                </a>
              </app-typography-h2>
              <app-typography-p class="text-sm text-slate-400">
                <span class="text-blue-400">{{
                  swebokFocusMap.get(path.swebokFocus)
                }}</span>
                • {{ path.courseCount }} Courses
              </app-typography-p>
            </header>

            <ul class="grid gap-2">
              @for (course of path.courses; track course._id) {
                <li
                  class="relative flex items-center justify-between rounded bg-slate-800/50 p-2 transition-colors hover:bg-slate-800"
                >
                  <div class="flex flex-col">
                    <a
                      class="text-sm font-medium text-slate-200 after:absolute after:inset-0 hover:text-blue-400 hover:underline"
                      target="_blank"
                      [href]="course.url"
                    >
                      {{ course.name }}
                    </a>
                    <span class="text-xs text-slate-500">{{
                      course.author
                    }}</span>
                  </div>
                  <div class="text-xs font-mono text-sky-300">
                    #{{ course.globalIndex }}
                  </div>
                </li>
              }
            </ul>
          </section>
        }
      </div>
    }
  </div>
</app-main-layout>

// apps/ethang/src/routes/courses.tsx
import { CourseAccordion } from "../components/courses/course-accordion.tsx";
import { MainLayout } from "../components/main-layout.tsx";
import { TypographyH1 } from "../components/typography/typography-h1.tsx";
import { TypographyP } from "../components/typography/typography-p.tsx";

const RouteComponent = () => {
  return (
    <MainLayout>
      <TypographyH1>Recommended Courses</TypographyH1>
      <TypographyP>
        This list is meant as a way to provide a straightforward curriculum of
        what you need to learn for development. It's updated constantly, but at
        any given point in time, I believe this is the best way to get started
        with, and learn everything you need to know to work with the web and
        beyond.
      </TypographyP>
      <TypographyP>
        These courses will take a while to get through, so I do recommend
        signing up for Pro accounts instead of buying one-time courses. I've
        optimized the list to focus on one platform at a time. When there is a
        series of Udemy courses, sign up for Udemy Pro, cancel it when your
        done, and so on.
      </TypographyP>

      <CourseAccordion />
    </MainLayout>
  );
};

export const Route = createFileRoute({
  component: RouteComponent,
});
